### ISSUE TITLE
希望能支持抖音Google Play版16.4.9

### ISSUE THREAD

**Issue by ajmz** [V-E-O/biliSpeed#14]
酷安的APP评论区看到的，有截图和下载链接，应该不是修改版，测试了能正常登录。

国区版是越来越臃肿。

另外，还有Instagram Lite。

![1000053453.jpg](https://github.com/V-E-O/biliSpeed/assets/30185045/0af96994-ae3a-41d9-bfbc-63f24ef9f5ba)

**Comment by V-E-O** [comment]
大概率包名不在里面, 试试这个
[app-release.zip](https://github.com/V-E-O/biliSpeed/files/14136075/app-release.zip)

**Comment by ajmz** [comment]
> 大概率包名不在里面, 试试这个 [app-release.zip](https://github.com/V-E-O/biliSpeed/files/14136075/app-release.zip)

请问zip格式的模块，是用什么方式安装，LSPosed ？

**Comment by V-E-O** [comment]
重命名为apk

**Comment by ajmz** [comment]
> 重命名为apk

重命名后安装了，启用模块里也选了，手机也重启了，但是调速抖音Google Play版16.4.9没有生效，在抖音极速版、小红书、bilibili和X上都可以。
![Screenshot_20240202225242](https://github.com/V-E-O/biliSpeed/assets/30185045/0530708d-10f1-4b3e-85c0-a5b6c85af0f1)

**Comment by V-E-O** [comment]
快速适配了下, fixed in version 1.1.5
后期大概率不维护这个版本
