### ISSUE TITLE
com.bilibili.app.in 3.16不支持

### ISSUE THREAD

**Issue by Sev73n** [V-E-O/biliSpeed#4]
国际版哔哩哔哩 希望能支持一下😘

**Comment by V-E-O** [comment]
酷安上有人测试316可以工作啊

**Comment by Sev73n** [comment]
![Screenshot_2023-05-06-13-41-42-220_com.bilibili.app.in.jpg](https://user-images.githubusercontent.com/16495885/236602698-27f40e1c-564f-4f72-b398-36dd9082888e.jpg)![Screenshot_2023-05-06-13-41-51-754_com.android.shell.jpg](https://user-images.githubusercontent.com/16495885/236602701-5069103e-ae02-473f-a906-56ffcc14fa0b.jpg)

奇怪我这里就不行 哔哩哔哩漫游我都没开 只有调速插件hook了

**Comment by V-E-O** [comment]
lsposed清除日志后传上来

**Comment by Sev73n** [comment]
[LSPosed_2023-05-06T18_03_08.614133.zip](https://github.com/V-E-O/biliSpeed/files/11412060/LSPosed_2023-05-06T18_03_08.614133.zip)
[LSPosed_2023-05-06T18_03_32.184474.zip](https://github.com/V-E-O/biliSpeed/files/11412061/LSPosed_2023-05-06T18_03_32.184474.zip)

**Comment by V-E-O** [comment]
[app-release.zip](https://github.com/V-E-O/biliSpeed/files/11412190/app-release.zip)

试试这个

**Comment by Sev73n** [comment]
> [app-release.zip](https://github.com/V-E-O/biliSpeed/files/11412190/app-release.zip)
> 
> 试试这个

ok！ 没问题了！感谢

**Comment by ajmz** [comment]
3.18版本还不支持？

**Comment by ajmz** [comment]
> [app-release.zip](https://github.com/V-E-O/biliSpeed/files/11412190/app-release.zip)
> 
> 试试这个

1.0.8，com.bilibili.app.in 3.18，停用了其他B站插件，还是不行。
